test:test
삼성스토어 수정
https://millietown.atlassian.net/browse/TECHQA-3240 (퀵 위젯 잘림 수정)
https://millietown.atlassian.net/browse/TECHCLIENT-256 (미구독 둥둥이 위치 수정)

diff --git a/.github/workflows/android-only-test.yml b/.github/workflows/android-only-test.yml
--- a/.github/workflows/android-only-test.yml
+++ b/.github/workflows/android-only-test.yml
@@ -67,194 +67,209 @@ jobs:
         run: |
           echo "description=true" >> $GITHUB_ENV
 
-      - name: Record Start Time
-        id: start_time
-        run: echo "workflow_start_time=$(date +%s)" >> $GITHUB_ENV
-
-      - name: Set Build Number
-        id: set_build_number
-        run: echo "BUILD_NUMBER=${{ github.run_number }}" >> $GITHUB_ENV
-
-
-      - name: Set up JDK 17
-        run: |
-          export JAVA_HOME=/opt/homebrew/Cellar/openjdk@17/17.0.7/libexec/openjdk.jdk/Contents/Home
-          export PATH=$JAVA_HOME/bin:$PATH
-          echo "JAVA_HOME=$JAVA_HOME" >> $GITHUB_ENV
-          echo "$JAVA_HOME/bin" >> $GITHUB_PATH
-
-      - name: Verify Java version
-        run: java -version
-
-      - name: Grant Execute Permission For Gradlew
-        run: chmod +x gradlew
-
-      - name: Create local.properties
-        run: |
-          echo "sdk.dir=$HOME/AndroidSDK" > $GITHUB_WORKSPACE/local.properties
+#      - name: Record Start Time
+#        id: start_time
+#        run: echo "workflow_start_time=$(date +%s)" >> $GITHUB_ENV
+#
+#      - name: Set Build Number
+#        id: set_build_number
+#        run: echo "BUILD_NUMBER=${{ github.run_number }}" >> $GITHUB_ENV
+#
+#
+#      - name: Set up JDK 17
+#        run: |
+#          export JAVA_HOME=/opt/homebrew/Cellar/openjdk@17/17.0.7/libexec/openjdk.jdk/Contents/Home
+#          export PATH=$JAVA_HOME/bin:$PATH
+#          echo "JAVA_HOME=$JAVA_HOME" >> $GITHUB_ENV
+#          echo "$JAVA_HOME/bin" >> $GITHUB_PATH
+#
+#      - name: Verify Java version
+#        run: java -version
+#
+#      - name: Grant Execute Permission For Gradlew
+#        run: chmod +x gradlew
+#
+#      - name: Create local.properties
+#        run: |
+#          echo "sdk.dir=$HOME/AndroidSDK" > $GITHUB_WORKSPACE/local.properties
       #
       #      - name: Clean Gradle Cache
       #        run: ./gradlew clean
 
 
-      - name: Build release Apk
-        run: ./gradlew ${{ matrix.task }} --stacktrace
-
-      - name: Find APK
-        id: find_apk
-        run: |
-          BUILD_NUMBER=${{ env.BUILD_NUMBER }}
-          TASK_NAME=${{ matrix.task }}
-          APK_NAME=""
-          APK_PATH=""
-
-          # Determine APK name and path based on task
-          case $TASK_NAME in
-            assembleGoogleDistributionRelease)
-              APK_NAME="app-google-distribution-release-${BUILD_NUMBER}.apk"
-              APK_PATH=$(find app/build/outputs/apk/googleDistribution/release/ -name "*.apk" | head -n 1)
-              ;;
-            assembleGoogleSandboxRelease)
-              APK_NAME="app-google-sandbox-release-${BUILD_NUMBER}.apk"
-              APK_PATH=$(find app/build/outputs/apk/googleSandbox/release/ -name "*.apk" | head -n 1)
-              ;;
-            assembleGoogleQaRelease)
-              APK_NAME="app-google-qa-release-${BUILD_NUMBER}.apk"
-              APK_PATH=$(find app/build/outputs/apk/googleQa/release/ -name "*.apk" | head -n 1)
-              ;;
-            assembleSamsungDistributionRelease)
-              APK_NAME="app-samsung-distribution-release-${BUILD_NUMBER}.apk"
-              APK_PATH=$(find app/build/outputs/apk/samsungDistribution/release/ -name "*.apk" | head -n 1)
-              ;;
-            assembleSamsungSandboxRelease)
-              APK_NAME="app-samsung-sandbox-release-${BUILD_NUMBER}.apk"
-              APK_PATH=$(find app/build/outputs/apk/samsungSandbox/release/ -name "*.apk" | head -n 1)
-              ;;
-            assembleSamsungQaRelease)
-              APK_NAME="app-samsung-qa-release-${BUILD_NUMBER}.apk"
-              APK_PATH=$(find app/build/outputs/apk/samsungQa/release/ -name "*.apk" | head -n 1)
-              ;;
-            assembleOnestoreDistributionRelease)
-              APK_NAME="app-onestore-distribution-release-${BUILD_NUMBER}.apk"
-              APK_PATH=$(find app/build/outputs/apk/onestoreDistribution/release/ -name "*.apk" | head -n 1)
-              ;;
-            assembleOnestoreSandboxRelease)
-              APK_NAME="app-onestore-sandbox-release-${BUILD_NUMBER}.apk"
-              APK_PATH=$(find app/build/outputs/apk/onestoreSandbox/release/ -name "*.apk" | head -n 1)
-              ;;
-            assembleOnestoreQaRelease)
-              APK_NAME="app-onestore-qa-release-${BUILD_NUMBER}.apk"
-              APK_PATH=$(find app/build/outputs/apk/onestoreQa/release/ -name "*.apk" | head -n 1)
-              ;;
-            *)
-              echo "Unknown task: $TASK_NAME"
-              exit 1
-              ;;
-          esac
-
-          if [ -z "$APK_PATH" ]; then
-            echo "APK not found for task: $TASK_NAME"
-            exit 1
-          fi
-
-          NEW_APK_PATH="${APK_PATH%/*}/$APK_NAME"
-          APK_DIR=$(dirname "$APK_PATH")
-          mv $APK_PATH $NEW_APK_PATH
-          echo "APK_PATH=$NEW_APK_PATH" >> $GITHUB_ENV
-          echo "APK_NAME=$APK_NAME" >> $GITHUB_ENV
-          echo "APK_DIR=$APK_DIR" >> $GITHUB_ENV
-
-      - name: Upload APK
-        uses: actions/upload-artifact@v4
-        with:
-          name: ${{ env.APK_NAME }}
-          path: ${{ env.APK_PATH }}
-          retention-days: 3
-
-      - name: Delete APK
-        run: |
-          rm -f ${{ env.APK_PATH }}
-
-      - name: Record End time
-        id: end_time
-        run: echo "workflow_end_time=$(date +%s)" >> $GITHUB_ENV
-
-
-      - name: Calculate Total Duration
-        id: total_duration
-        run: |
-          workflow_start_time=${{ env.workflow_start_time }}
-          workflow_end_time=${{ env.workflow_end_time }}
-          total_duration=$((workflow_end_time - workflow_start_time))
-          if [ $total_duration -lt 60 ]; then
-            total_duration_formatted="${total_duration}초"
-          else
-            total_minutes=$((total_duration / 60))
-            total_seconds=$((total_duration % 60))
-            total_duration_formatted="${total_minutes}분 ${total_seconds}초"
-          fi
-          echo "Total duration: $total_duration_formatted"
-          echo "total_duration_formatted=$total_duration_formatted" >> $GITHUB_ENV
-
-#  notify:
-#    runs-on: ubuntu-latest
-#    needs: build
-#    steps:
+#      - name: Build release Apk
+#        run: ./gradlew ${{ matrix.task }} --stacktrace
 #
+#      - name: Find APK
+#        id: find_apk
+#        run: |
+#          BUILD_NUMBER=${{ env.BUILD_NUMBER }}
+#          TASK_NAME=${{ matrix.task }}
+#          APK_NAME=""
+#          APK_PATH=""
 #
-#      - name: Send Build Status Slack Msg
-#        uses: 8398a7/action-slack@v3
-#        env:
-#          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_PERSONAL_WEB_HOOK_URL }}
+#          # Determine APK name and path based on task
+#          case $TASK_NAME in
+#            assembleGoogleDistributionRelease)
+#              APK_NAME="app-google-distribution-release-${BUILD_NUMBER}.apk"
+#              APK_PATH=$(find app/build/outputs/apk/googleDistribution/release/ -name "*.apk" | head -n 1)
+#              ;;
+#            assembleGoogleSandboxRelease)
+#              APK_NAME="app-google-sandbox-release-${BUILD_NUMBER}.apk"
+#              APK_PATH=$(find app/build/outputs/apk/googleSandbox/release/ -name "*.apk" | head -n 1)
+#              ;;
+#            assembleGoogleQaRelease)
+#              APK_NAME="app-google-qa-release-${BUILD_NUMBER}.apk"
+#              APK_PATH=$(find app/build/outputs/apk/googleQa/release/ -name "*.apk" | head -n 1)
+#              ;;
+#            assembleSamsungDistributionRelease)
+#              APK_NAME="app-samsung-distribution-release-${BUILD_NUMBER}.apk"
+#              APK_PATH=$(find app/build/outputs/apk/samsungDistribution/release/ -name "*.apk" | head -n 1)
+#              ;;
+#            assembleSamsungSandboxRelease)
+#              APK_NAME="app-samsung-sandbox-release-${BUILD_NUMBER}.apk"
+#              APK_PATH=$(find app/build/outputs/apk/samsungSandbox/release/ -name "*.apk" | head -n 1)
+#              ;;
+#            assembleSamsungQaRelease)
+#              APK_NAME="app-samsung-qa-release-${BUILD_NUMBER}.apk"
+#              APK_PATH=$(find app/build/outputs/apk/samsungQa/release/ -name "*.apk" | head -n 1)
+#              ;;
+#            assembleOnestoreDistributionRelease)
+#              APK_NAME="app-onestore-distribution-release-${BUILD_NUMBER}.apk"
+#              APK_PATH=$(find app/build/outputs/apk/onestoreDistribution/release/ -name "*.apk" | head -n 1)
+#              ;;
+#            assembleOnestoreSandboxRelease)
+#              APK_NAME="app-onestore-sandbox-release-${BUILD_NUMBER}.apk"
+#              APK_PATH=$(find app/build/outputs/apk/onestoreSandbox/release/ -name "*.apk" | head -n 1)
+#              ;;
+#            assembleOnestoreQaRelease)
+#              APK_NAME="app-onestore-qa-release-${BUILD_NUMBER}.apk"
+#              APK_PATH=$(find app/build/outputs/apk/onestoreQa/release/ -name "*.apk" | head -n 1)
+#              ;;
+#            *)
+#              echo "Unknown task: $TASK_NAME"
+#              exit 1
+#              ;;
+#          esac
+#
+#          if [ -z "$APK_PATH" ]; then
+#            echo "APK not found for task: $TASK_NAME"
+#            exit 1
+#          fi
+#
+#          NEW_APK_PATH="${APK_PATH%/*}/$APK_NAME"
+#          APK_DIR=$(dirname "$APK_PATH")
+#          mv $APK_PATH $NEW_APK_PATH
+#          echo "APK_PATH=$NEW_APK_PATH" >> $GITHUB_ENV
+#          echo "APK_NAME=$APK_NAME" >> $GITHUB_ENV
+#          echo "APK_DIR=$APK_DIR" >> $GITHUB_ENV
+#
+#      - name: Upload APK
+#        uses: actions/upload-artifact@v4
 #        with:
-#          status: custom
-#          custom_payload: |
-#            {
-#              "attachments": [
-#                {
-#                  "color": "${{ needs.build.result == 'success' && '#36a64f' || '#FF0000' }}",
-#                  "title": "AOS Release Build",
-#                 "fields": [
-#                    {
-#                      "title": "변경점",
-#                      "value": "`${{ env.COMMIT_MESSAGE }}`",
-#                      "short": false
-#                  },
-#                 {
-#                      "title": "커밋 설명",
-#                      "value": "`${{ env.COMMIT_DESCRIPTION }}`",
-#                      "short": false
-#                    },
-#                  {
-#                  "title": "다운로드 주소",
-#                  "value": "<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}>",
-#                  "short": false
-#                  },
-#                  {
-#                     "title": "브랜치",
-#                     "value": "`${{ env.BRANCH_NAME }}`",
-#                     "short": true
-#                   },
-#                   {
-#                     "title": "이벤트 이름",
-#                     "value": "_${{github.event_name}}_",
-#                     "short": true
-#                   },
-#                   {
-#                     "title": "작성자",
-#                     "value": "*${{ github.event.head_commit.author.name }}*",
-#                     "short": true
-#                   },
-#                  {
-#                    "title": "담당자",
-#                    "value": "abc",
-#                     "short": false
-#                   }
-#                 ],
-#                  "footer": "Build Notification",
-#                  "footer_icon": "https://cdn-icons-png.flaticon.com/512/226/226770.png"
-#                }
-#              ]
-#            }
-#        if: ${{ needs.build.result == 'success' }}
+#          name: ${{ env.APK_NAME }}
+#          path: ${{ env.APK_PATH }}
+#          retention-days: 3
+#
+#      - name: Delete APK
+#        run: |
+#          rm -f ${{ env.APK_PATH }}
+#
+#      - name: Record End time
+#        id: end_time
+#        run: echo "workflow_end_time=$(date +%s)" >> $GITHUB_ENV
+#
+#
+#      - name: Calculate Total Duration
+#        id: total_duration
+#        run: |
+#          workflow_start_time=${{ env.workflow_start_time }}
+#          workflow_end_time=${{ env.workflow_end_time }}
+#          total_duration=$((workflow_end_time - workflow_start_time))
+#          if [ $total_duration -lt 60 ]; then
+#            total_duration_formatted="${total_duration}초"
+#          else
+#            total_minutes=$((total_duration / 60))
+#            total_seconds=$((total_duration % 60))
+#            total_duration_formatted="${total_minutes}분 ${total_seconds}초"
+#          fi
+#          echo "Total duration: $total_duration_formatted"
+#          echo "total_duration_formatted=$total_duration_formatted" >> $GITHUB_ENV
+
+  notify:
+    runs-on: ubuntu-latest
+    needs: build
+    steps:
+
+      - name: Checkout code for commit messages
+        uses: actions/checkout@v4
+
+      - name: Fetch Branch and Commit Messages
+        id: fetch_info
+        run: |
+          # Extract branch name without prefix
+          BRANCH_NAME=$(echo "${{ github.ref_name }}" | sed 's/^[^/]*\///')
+          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
+
+          COMMIT_MESSAGE=$(git log -1 --pretty=%s ${{ github.sha }})
+          COMMIT_DESCRIPTION=$(git log -1 --pretty=%b ${{ github.sha }} | tr '\n' ' ')
+
+          echo "COMMIT_MESSAGE=$COMMIT_MESSAGE" >> $GITHUB_ENV
+          echo "COMMIT_DESCRIPTION=$COMMIT_DESCRIPTION" >> $GITHUB_ENV
+
+      - name: Send Build Status Slack Msg
+        uses: 8398a7/action-slack@v3
+        env:
+          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_PERSONAL_WEB_HOOK_URL }}
+        with:
+          status: custom
+          custom_payload: |
+            {
+              "attachments": [
+                {
+                  "color": "${{ needs.build.result == 'success' && '#36a64f' || '#FF0000' }}",
+                  "title": "AOS Release Build",
+                 "fields": [
+                    {
+                      "title": "변경점",
+                      "value": "`${{ env.COMMIT_MESSAGE }}`",
+                      "short": false
+                  },
+                 {
+                      "title": "커밋 설명",
+                      "value": "`${{ env.COMMIT_DESCRIPTION }}`",
+                      "short": false
+                    },
+                  {
+                  "title": "다운로드 주소",
+                  "value": "<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}>",
+                  "short": false
+                  },
+                  {
+                     "title": "브랜치",
+                     "value": "`${{ env.BRANCH_NAME }}`",
+                     "short": true
+                   },
+                   {
+                     "title": "이벤트 이름",
+                     "value": "_${{github.event_name}}_",
+                     "short": true
+                   },
+                   {
+                     "title": "작성자",
+                     "value": "*${{ github.event.head_commit.author.name }}*",
+                     "short": true
+                   },
+                  {
+                    "title": "담당자",
+                    "value": "abc",
+                     "short": false
+                   }
+                 ],
+                  "footer": "Build Notification",
+                  "footer_icon": "https://cdn-icons-png.flaticon.com/512/226/226770.png"
+                }
+              ]
+            }
+        if: ${{ needs.build.result == 'success' }}
 
