test: 귀차나
rnlcsersa

diff --git a/.github/workflows/android-only-test.yml b/.github/workflows/android-only-test.yml
--- a/.github/workflows/android-only-test.yml
+++ b/.github/workflows/android-only-test.yml
@@ -94,83 +94,83 @@ jobs:
 #      - name: Clean Gradle Cache
 #        run: ./gradlew clean
 
-      - name: Build release Apk
-        run: ./gradlew ${{ matrix.task }} --stacktrace
-
-      - name: Find APK
-        id: find_apk
-        run: |
-          BUILD_NUMBER=${{ env.BUILD_NUMBER }}
-          TASK_NAME=${{ matrix.task }}
-          APK_NAME=""
-          APK_PATH=""
-
-          # Determine APK name and path based on task
-          case $TASK_NAME in
-            assembleGoogleDistributionRelease)
-              APK_NAME="app-google-distribution-release-${BUILD_NUMBER}.apk"
-              APK_PATH=$(find app/build/outputs/apk/googleDistribution/release/ -name "*.apk" | head -n 1)
-              ;;
-            assembleGoogleSandboxRelease)
-              APK_NAME="app-google-sandbox-release-${BUILD_NUMBER}.apk"
-              APK_PATH=$(find app/build/outputs/apk/googleSandbox/release/ -name "*.apk" | head -n 1)
-              ;;
-            assembleGoogleQaRelease)
-              APK_NAME="app-google-qa-release-${BUILD_NUMBER}.apk"
-              APK_PATH=$(find app/build/outputs/apk/googleQa/release/ -name "*.apk" | head -n 1)
-              ;;
-            assembleSamsungDistributionRelease)
-              APK_NAME="app-samsung-distribution-release-${BUILD_NUMBER}.apk"
-              APK_PATH=$(find app/build/outputs/apk/samsungDistribution/release/ -name "*.apk" | head -n 1)
-              ;;
-            assembleSamsungSandboxRelease)
-              APK_NAME="app-samsung-sandbox-release-${BUILD_NUMBER}.apk"
-              APK_PATH=$(find app/build/outputs/apk/samsungSandbox/release/ -name "*.apk" | head -n 1)
-              ;;
-            assembleSamsungQaRelease)
-              APK_NAME="app-samsung-qa-release-${BUILD_NUMBER}.apk"
-              APK_PATH=$(find app/build/outputs/apk/samsungQa/release/ -name "*.apk" | head -n 1)
-              ;;
-            assembleOnestoreDistributionRelease)
-              APK_NAME="app-onestore-distribution-release-${BUILD_NUMBER}.apk"
-              APK_PATH=$(find app/build/outputs/apk/onestoreDistribution/release/ -name "*.apk" | head -n 1)
-              ;;
-            assembleOnestoreSandboxRelease)
-              APK_NAME="app-onestore-sandbox-release-${BUILD_NUMBER}.apk"
-              APK_PATH=$(find app/build/outputs/apk/onestoreSandbox/release/ -name "*.apk" | head -n 1)
-              ;;
-            assembleOnestoreQaRelease)
-              APK_NAME="app-onestore-qa-release-${BUILD_NUMBER}.apk"
-              APK_PATH=$(find app/build/outputs/apk/onestoreQa/release/ -name "*.apk" | head -n 1)
-              ;;
-            *)
-              echo "Unknown task: $TASK_NAME"
-              exit 1
-              ;;
-          esac
-
-          if [ -z "$APK_PATH" ]; then
-            echo "APK not found for task: $TASK_NAME"
-            exit 1
-          fi
-
-          NEW_APK_PATH="${APK_PATH%/*}/$APK_NAME"
-          APK_DIR=$(dirname "$APK_PATH")
-          mv $APK_PATH $NEW_APK_PATH
-          echo "APK_PATH=$NEW_APK_PATH" >> $GITHUB_ENV
-          echo "APK_NAME=$APK_NAME" >> $GITHUB_ENV
-          echo "APK_DIR=$APK_DIR" >> $GITHUB_ENV
-
-      - name: Upload APK
-        uses: actions/upload-artifact@v4
-        with:
-          name: ${{ env.APK_NAME }}
-          path: ${{ env.APK_PATH }}
-          retention-days: 3
-
-      - name: Delete APK
-        run: |
-          rm -f ${{ env.APK_PATH }}
+#      - name: Build release Apk
+#        run: ./gradlew ${{ matrix.task }} --stacktrace
+#
+#      - name: Find APK
+#        id: find_apk
+#        run: |
+#          BUILD_NUMBER=${{ env.BUILD_NUMBER }}
+#          TASK_NAME=${{ matrix.task }}
+#          APK_NAME=""
+#          APK_PATH=""
+#
+#          # Determine APK name and path based on task
+#          case $TASK_NAME in
+#            assembleGoogleDistributionRelease)
+#              APK_NAME="app-google-distribution-release-${BUILD_NUMBER}.apk"
+#              APK_PATH=$(find app/build/outputs/apk/googleDistribution/release/ -name "*.apk" | head -n 1)
+#              ;;
+#            assembleGoogleSandboxRelease)
+#              APK_NAME="app-google-sandbox-release-${BUILD_NUMBER}.apk"
+#              APK_PATH=$(find app/build/outputs/apk/googleSandbox/release/ -name "*.apk" | head -n 1)
+#              ;;
+#            assembleGoogleQaRelease)
+#              APK_NAME="app-google-qa-release-${BUILD_NUMBER}.apk"
+#              APK_PATH=$(find app/build/outputs/apk/googleQa/release/ -name "*.apk" | head -n 1)
+#              ;;
+#            assembleSamsungDistributionRelease)
+#              APK_NAME="app-samsung-distribution-release-${BUILD_NUMBER}.apk"
+#              APK_PATH=$(find app/build/outputs/apk/samsungDistribution/release/ -name "*.apk" | head -n 1)
+#              ;;
+#            assembleSamsungSandboxRelease)
+#              APK_NAME="app-samsung-sandbox-release-${BUILD_NUMBER}.apk"
+#              APK_PATH=$(find app/build/outputs/apk/samsungSandbox/release/ -name "*.apk" | head -n 1)
+#              ;;
+#            assembleSamsungQaRelease)
+#              APK_NAME="app-samsung-qa-release-${BUILD_NUMBER}.apk"
+#              APK_PATH=$(find app/build/outputs/apk/samsungQa/release/ -name "*.apk" | head -n 1)
+#              ;;
+#            assembleOnestoreDistributionRelease)
+#              APK_NAME="app-onestore-distribution-release-${BUILD_NUMBER}.apk"
+#              APK_PATH=$(find app/build/outputs/apk/onestoreDistribution/release/ -name "*.apk" | head -n 1)
+#              ;;
+#            assembleOnestoreSandboxRelease)
+#              APK_NAME="app-onestore-sandbox-release-${BUILD_NUMBER}.apk"
+#              APK_PATH=$(find app/build/outputs/apk/onestoreSandbox/release/ -name "*.apk" | head -n 1)
+#              ;;
+#            assembleOnestoreQaRelease)
+#              APK_NAME="app-onestore-qa-release-${BUILD_NUMBER}.apk"
+#              APK_PATH=$(find app/build/outputs/apk/onestoreQa/release/ -name "*.apk" | head -n 1)
+#              ;;
+#            *)
+#              echo "Unknown task: $TASK_NAME"
+#              exit 1
+#              ;;
+#          esac
+#
+#          if [ -z "$APK_PATH" ]; then
+#            echo "APK not found for task: $TASK_NAME"
+#            exit 1
+#          fi
+#
+#          NEW_APK_PATH="${APK_PATH%/*}/$APK_NAME"
+#          APK_DIR=$(dirname "$APK_PATH")
+#          mv $APK_PATH $NEW_APK_PATH
+#          echo "APK_PATH=$NEW_APK_PATH" >> $GITHUB_ENV
+#          echo "APK_NAME=$APK_NAME" >> $GITHUB_ENV
+#          echo "APK_DIR=$APK_DIR" >> $GITHUB_ENV
+#
+#      - name: Upload APK
+#        uses: actions/upload-artifact@v4
+#        with:
+#          name: ${{ env.APK_NAME }}
+#          path: ${{ env.APK_PATH }}
+#          retention-days: 3
+#
+#      - name: Delete APK
+#        run: |
+#          rm -f ${{ env.APK_PATH }}
 
       - name: Record End time
         id: end_time
